/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hpg.common.biz.service.abstr;

import java.util.function.Function;
import org.hpg.common.model.exception.MendelRuntimeException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Abstract class for paging service
 *
 * @author wws2003
 * @param <T>
 */
public interface IPagingService<T> {

    // TOOD Add more methods
    /**
     * Get data for current page
     *
     * @param pageRequest
     * @return
     * @throws MendelRuntimeException When find operation failed
     */
    public Page<T> getPage(Pageable pageRequest) throws MendelRuntimeException;

    /**
     * Get data for current page generated by mapping function
     *
     * @param <T1>
     * @param pageRequest
     * @param mapFunc
     * @return
     * @throws MendelRuntimeException When find operation failed
     */
    default public <T1> Page<T1> getPage(Pageable pageRequest, Function<T, T1> mapFunc) throws MendelRuntimeException {
        return getPage(pageRequest).map(mapFunc);
    }

}
