-- Choose the Database
\c  :v1;

-- Triggers and functions
DROP TRIGGER IF EXISTS TRG_UPDATE_MDATE ON TBL_PROJECT;
DROP FUNCTION IF EXISTS FUNC_UPDATE_MDATE;

-- POSTIT
DROP TABLE IF EXISTS TBL_POSTIT;

-- Page
DROP TABLE IF EXISTS TBL_PAGE;

-- References across documents
DROP TABLE IF EXISTS TBL_DOCUMENT_REFERENCE;

-- Document
DROP TABLE IF EXISTS TBL_DOCUMENT;

-- User-Project map
DROP TABLE IF EXISTS TBL_USER_PROJECT;

-- Project
DROP TABLE IF EXISTS TBL_PROJECT;

-- User-Privilege map
DROP TABLE IF EXISTS TBL_USER_PRIV;

-- User
DROP TABLE IF EXISTS TBL_USER;

-- Privilege
DROP TABLE IF EXISTS TBL_PRIVILEGE;

-- Role
DROP TABLE IF EXISTS TBL_ROLE;
