-- Choose the Database
\c  :v1;

-- POSTIT
DROP TABLE IF EXISTS TBL_POSTIT;

-- References across documents
DROP TABLE IF EXISTS TBL_DOCUMENT_REFERENCE;

-- Document
DROP TABLE IF EXISTS TBL_DOCUMENT;

-- Project
DROP TABLE IF EXISTS TBL_PROJECT;

-- User-Project map
DROP TABLE IF EXISTS TBL_USER_PROJECT;

-- User-Privilege map
DROP TABLE IF EXISTS TBL_USER_PRIV;

-- User
DROP TABLE IF EXISTS TBL_USER;

-- Privilege
DROP TABLE IF EXISTS TBL_PRIVILEGE;

-- Role
DROP TABLE IF EXISTS TBL_ROLE;
